name: 'Publish to Confluence'
description: 'Publish a new page to a Confluence site'
inputs:
  type:
    description: 'Confluence content type'
    required: true
    default: 'page'
  title:
    description: 'Confluence content title'
    required: true
  body:
    description: 'Confluence content body'
    required: true
  representation:
    description: 'Confluence content representation'
    required: true
    default: 'storage'
  space:
    description: 'Confluence space key'
    required: true
  parent_id:
    description: 'ID of parent page in Confluence'
    required: true
  hostname:
    description: 'Confluence hostname'
    required: true
  username:
    description: 'Confluence API user email'
    required: true
outputs:
  reponse: # output will be available to future steps
    description: 'The response from the Confluence API'
runs:
  using: 'node12'
  main: 'dist/index.js'
